SDC = {}

---------------------------------------------------------------------------------
-------------------------------Important Configs---------------------------------
---------------------------------------------------------------------------------
SDC.Framework = "qb-core" --Either "qb-core" or "esx"
SDC.NotificationSystem = "framework" -- ['mythic_old', 'mythic_new', 'tnotify', 'okoknotify', 'ox_lib', 'print', 'framework', 'none'] --Notification system you prefer to use
SDC.UseProgBar = "ox_lib" --If you want to use a progress bar resource, options: ["progressBars", "mythic_progbar", "ox_lib", "none"]

SDC.PoliceJobs = {
    --EX: ["job_name"] = "JOB_LABEL"

    ["police"] = "Police"
}

SDC.CurrentYear = 2024 --The current year we are in. This is to make correct Date Of Births

SDC.DistToCancelPullover = 65 --How far you have to be from the ped before it auto cancels the pullover

SDC.PulloverCooldown = 15 --How often you can pull someone over (In Seconds)

SDC.PayoutSettings = { --All payout configs
    PerCitation = 500, --How much you earn per citation
    PerJailing = 3000, --How much you earn per jailing
    PerChase = 1000 --How much you earn per pursuit
}

---------------------------------------------------------------------------------
-------------------------------Keybinds Configs----------------------------------
---------------------------------------------------------------------------------
SDC.PulloverKeybinds = { --Main pullover settings
    CommandName = "sdap:pulloverai", --Name of the command to pullover car in front
    Keybind = { --Kebind settings for Pullover
        Enabled = true, --If you want the keybind to be enabled
        Key = "H" --Default Keybind (All Players Can Change In Game Keybinds)
    }
}

SDC.ConfirmPulloverKeys = { --Keys for confirming/canceling pullover
    Exit = {Input = "INPUT_DETONATE", InputNum = 47},
    Confirm = {Input = "INPUT_PICKUP", InputNum = 38},
}
SDC.ConfirmPulloverKeys = { --Keys for setting desired location with birds eye view
    Exit = {Input = "INPUT_DETONATE", InputNum = 47},
    Confirm = {Input = "INPUT_PICKUP", InputNum = 38},
    Forward = {Input = "INPUT_MOVE_UP_ONLY", InputNum = 32},
    Backward = {Input = "INPUT_MOVE_DOWN_ONLY", InputNum = 33},
    Left = {Input = "INPUT_MOVE_LEFT_ONLY", InputNum = 34},
    Right = {Input = "INPUT_MOVE_RIGHT_ONLY", InputNum = 35},
    RotateRight = {Input = "INPUT_WEAPON_WHEEL_NEXT", InputNum = 14},
    RotateLeft = {Input = "INPUT_WEAPON_WHEEL_PREV", InputNum = 15},
    ZoomIn = {Input = "INPUT_VEH_MOVE_DOWN_ONLY", InputNum = 62},
    ZoomOut = {Input = "INPUT_VEH_MOVE_UP_ONLY", InputNum = 61},
}
SDC.VehicleSearchKeys = { --Keys for searching vehicle
    Exit = {Input = "INPUT_DETONATE", InputNum = 47},
    Search = {Input = "INPUT_PICKUP", InputNum = 38},
}
SDC.ChaseKeys = { --Keys for vehicle chases
    Exit = {Input = "INPUT_DETONATE", InputNum = 47},
}
---------------------------------------------------------------------------------
-------------------------------Jail Configs--------------------------------------
---------------------------------------------------------------------------------
SDC.JailingLocations = {
    --EX: {Label = "LABEL_OF_LOCATION", Coords = vec3(0.0, 0.0, 0.0), DistToJail = 8}, --DistToJail Is How Close They Have To Be To Those Coords To Jail Ped

    {Label = "MRPD", Coords = vec3(459.7438, -998.0081, 24.9149), DistToJail = 8},
}

---------------------------------------------------------------------------------
-------------------------------Pullover Configs----------------------------------
---------------------------------------------------------------------------------
SDC.BirdsEyeOffsetHeights = { --Offsets Heights For Birds Eye View (Zooming In And Out In Pullover Location)
    Min = 2.0, 
    Default = 10.0,
    Max = 15.0
}

SDC.DistToTalkToPed = 2.5 --How close you have to be to see interaction options for the ped

SDC.DistToInteractWithVehicle = 3.0 --How close you have to be to see interaction options for the vehicle
SDC.DistToInteractWithSearch = 1.5 --How close you have to be to the search location to search that area

SDC.ChaseSettings = { --All Pursuit/Chase Settings
    Enabled = true, --If you want pursuits to be enabled
    Chances = { --All Chances from 1-100
        ChanceToRunForNoReason = 0, --Chance for a ped to run for no reason
        ChanceToRunForWarrant = 40, --Chance for a ped to run for having a warrant
        ChanceToRunForIllegalItems = 20, --Chance for a ped to run for illegal items on them or in the car
        ChanceToRunForIllegalWeapons = 30, --Chance for a ped to run for illegal weapons on them or in the car

        ChanceToPullWeaponOnCopAfterChase = 80 --Chance for a ped to pull a weapon when the chase/pursuit is over (Must have a weapon on them or in car)
    },
    FleeTime = {Min = 1, Max = 2}, --How long a suspect can be fleeing for min, max (In Minutes)
    MaxChaseDist = 100 --How far you can be from the fleeing suspect before it cancels the pursuit
}

SDC.BreathalyzerSettings = { --All Breathalyzer Settings
    ChanceToHaveAlcoholInSystem = 40, --Chance from 1-100 for the ped to have alcohol in their system (Set to 0 to disable this feature)
    RandomLevels = {Min = 8, Max = 20} --Random Blood-Alcohol Level (Note This is divided by 100! For example the number 8 is actually 0.08% which is legal limit)
}

---------------------------------------------------------------------------------
-------------------------------Vehicle Configs-----------------------------------
---------------------------------------------------------------------------------
SDC.VehicleSettings = { --All Vehicle Settings For Registration 
    ChanceOfVehicleBeingRegistered = 85, --Chance That The Vehicle Is Registered 
    ChanceOfVehicleBeingStolen = 15, --Chance That The Vehicle Is Stolen (The Owner's Name Will Appear Different Then The Local Driving) 
    ChanceOfVehicleHavingUpdateTags = 80 --Chance That The Vehicle Has Updated Tags (Only Happens When Vehicle Is Registered)
}

SDC.VehClasses = { --All Vehicle Classes (DO NOT TOUCH)
    ["0"] = "Compacts",
    ["1"] = "Sedans",
    ["2"] = "SUVs",
    ["3"] = "Coupes",  
    ["4"] = "Muscle",  
    ["5"] = "Sports Classics", 
    ["6"] = "Sports",  
    ["7"] = "Super",  
    ["8"] = "Motorcycles",  
    ["9"] = "Off-road",  
    ["10"] = "Industrial",  
    ["11"] = "Utility",  
    ["12"] = "Vans",  
    ["13"] = "Cycles",  
    ["14"] = "Boats",  
    ["15"] = "Helicopters",  
    ["16"] = "Planes",  
    ["17"] = "Service",  
    ["18"] = "Emergency",  
    ["19"] = "Military",  
    ["20"] = "Commercial",  
    ["21"] = "Trains",  
    ["22"] = "Open Wheel"
}

---------------------------------------------------------------------------------
-------------------------------Ped Licenses Configs------------------------------
---------------------------------------------------------------------------------
SDC.Licenses = { --All License Configs
    --EX: ["unqiue_id"] = {Label = "LICENSE_LABEL", ChanceOfHaving = 100, ChanceOfBeingSuspended = 0}

    ["drivers"] = {Label = "Drivers License", ChanceOfHaving = 80, ChanceOfBeingSuspended = 20},
    ["motorcycle"] = {Label = "Motorcycle License", ChanceOfHaving = 80, ChanceOfBeingSuspended = 30},
    ["cdl"] = {Label = "CDL", ChanceOfHaving = 50, ChanceOfBeingSuspended = 10},
    ["concealedcarry"] = {Label = "Concealed Carry License", ChanceOfHaving = 40, ChanceOfBeingSuspended = 5},
    ["pilot"] = {Label = "Pilots License", ChanceOfHaving = 20, ChanceOfBeingSuspended = 5}
}

---------------------------------------------------------------------------------
-------------------------------Ped Warrant Configs-------------------------------
---------------------------------------------------------------------------------
SDC.WarrantChances = { --All Warrant Settings
    ChanceOfHavingWarrants = 30, --Chance Of Having A Warrant (Set to 0 to disabled)
    RandomWarrantCount = {Min = 1, Max = 3} --Random amount of warrants given
}
SDC.PossibleWarrants = { --All The Different Warrants
    --EX: "LABEL_FOR_WARRANT",

    "First Degree Murder",
    "Second Degree Murder",
    "Reckless Evading",
    "Assault",
    "Aggravated Assault",
    "Sexual Assault",
    "Gang Assault",
    "Burglary",
    "Armed Robbery",
    "Robbery",
    "Sexual Conduct Against A Child",
    "Criminal Possession Of A Weapon",
    "Criminal Sale Of A Firearm",
    "Criminal Use Of A Firearm",
    "Criminal Possession Of A Chemical Weapon",
    "Criminal Possession Of A Controlled Substance",
    "Criminal Sale Of A Controlled Substance",
    "Arson",
    "Rape",
    "Sodomy",
    "Voluntary Manslaughter",
    "Treason",
    "Kidnapping",
    "Human Trafficking",
    "Aggravated Insurance Fraud",
    "Bribery",
    "Bribe Receiving",
    "Conspiracy",
    "Grand Larceny",
    "Prostitution",
    "Tampering With A Witness",
    "Failure To Appear In Court",
    "Forgery"
}

---------------------------------------------------------------------------------
-------------------------------Search Configs------------------------------------
---------------------------------------------------------------------------------
SDC.SearchSettings = { --All Main Search Settings
    RandomItemCount = { --Random Item Settings
        OnLocal = {Min = 0, Max = 4}, --Amount of random items on local/in pockets
        InVehicle = {Min = 0, Max = 8}, --Amount of random items in the vehicle
    },
    RandomWeaponCount = { --Random Weapon Settings
        ChanceToHaveWeaponOnLocal = 25, --Chance for there to be a weapon on a local (Set to 0 to disable)
        OnLocal = {Min = 1, Max = 2},  --Amount of random weapons on local/in pockets

        ChanceToHaveWeaponInVehicle = 35, --Chance for there to be a weapon in the vehicle (Set to 0 to disable)
        InVehicle = {Min = 1, Max = 3}, --Amount of random weapons in the vehicle
    }
}
SDC.SearchWeapons = { --All Possible Weapons
    --EX: {Label = "LABEL_OF_WEAPON", Illegal = false, Location = 3, WeaponHash = "weapon_spawn_hash"}, --LOCATIONS: (1=Only On Ped, 2=Only In Vehicle, 3=Can Be In Both)

    {Label = "Crowbar", Illegal = false, Location = 3, WeaponHash = "weapon_crowbar"},
    {Label = "Golf Club", Illegal = false, Location = 2, WeaponHash = "weapon_golfclub"},
    {Label = "Wrench", Illegal = false, Location = 3, WeaponHash = "weapon_wrench"},
    {Label = "Knife", Illegal = false, Location = 3, WeaponHash = "weapon_knife"},
    {Label = "Nightstick", Illegal = true, Location = 3, WeaponHash = "weapon_nightstick"},
    {Label = "Pistol", Illegal = false, Location = 3, WeaponHash = "weapon_pistol"},
    {Label = "AP Pistol", Illegal = true, Location = 3, WeaponHash = "weapon_appistol"},
    {Label = "Revolver", Illegal = false, Location = 3, WeaponHash = "weapon_revolver"},
    {Label = "Mircro SMG", Illegal = true, Location = 3, WeaponHash = "weapon_microsmg"},
    {Label = "Pump Shotgun", Illegal = false, Location = 2, WeaponHash = "weapon_pumpshotgun"},
    {Label = "Assault Rifle", Illegal = true, Location = 2, WeaponHash = "weapon_assaultrifle"},
}
SDC.SearchItems = { --All Possible Items
    --EX: {Label = "LABEL_OF_ITEM", Illegal = false, Location = 3}, --LOCATIONS: (1=Only On Ped, 2=Only In Vehicle, 3=Can Be In Both)

    {Label = "Phone", Illegal = false, Location = 3},
    {Label = "Wallet", Illegal = false, Location = 3},
    {Label = "Loose Change", Illegal = false, Location = 3},
    {Label = "Store Reciept", Illegal = false, Location = 3},
    {Label = "Pocket Lint", Illegal = false, Location = 1},
    {Label = "Wrapper", Illegal = false, Location = 3},
    {Label = "Candy Bar", Illegal = false, Location = 3},
    {Label = "Empty Soda Can", Illegal = false, Location = 2},
    {Label = "Bag Of Trash", Illegal = false, Location = 2},
    {Label = "Trash", Illegal = false, Location = 3},
    {Label = "Note", Illegal = false, Location = 3},
    {Label = "Newspaper", Illegal = false, Location = 3},
    {Label = "Bus Ticket", Illegal = false, Location = 3},
    {Label = "Train Ticket", Illegal = false, Location = 3},
    {Label = "Airplane Ticket", Illegal = false, Location = 3},
    {Label = "Passport", Illegal = false, Location = 3},
    {Label = "Social Security Card", Illegal = false, Location = 3},
    {Label = "Debit Card", Illegal = false, Location = 3},
    {Label = "Credit Card", Illegal = false, Location = 3},
    {Label = "Phone Charger", Illegal = false, Location = 3},
    {Label = "Laptop", Illegal = false, Location = 2},
    {Label = "Makeup Brush", Illegal = false, Location = 3},
    {Label = "Dildo", Illegal = false, Location = 2},
    {Label = "Condom", Illegal = false, Location = 3},
    {Label = "Wedding Ring", Illegal = false, Location = 3},
    {Label = "Gold Chain", Illegal = false, Location = 3},
    {Label = "Jumper Cables", Illegal = false, Location = 2},
    {Label = "Fake ID", Illegal = true, Location = 3},
    {Label = "Hacker Phone", Illegal = true, Location = 3},
    {Label = "Pack Of Cigs", Illegal = false, Location = 3},
    {Label = "Lighter", Illegal = false, Location = 3},
    {Label = "Boosting Laptop", Illegal = true, Location = 2},
    {Label = "1oz Baggy Of Weed", Illegal = false, Location = 3},
    {Label = "1oz Baggy Of Cocaine", Illegal = true, Location = 3},
    {Label = "1oz Baggy Of Meth", Illegal = true, Location = 3},
    {Label = "1oz Baggy Of Shrooms", Illegal = true, Location = 3},
    {Label = "5oz Baggy Of Weed", Illegal = true, Location = 3},
    {Label = "5oz Baggy Of Cocaine", Illegal = true, Location = 3},
    {Label = "5oz Baggy Of Meth", Illegal = true, Location = 3},
    {Label = "5oz Baggy Of Shrooms", Illegal = true, Location = 3},
    {Label = "20oz Bag Of Weed", Illegal = true, Location = 2},
    {Label = "20oz Brick Of Cocaine", Illegal = true, Location = 2},
    {Label = "20oz Bag Of Meth", Illegal = true, Location = 2},
    {Label = "20oz Bag Of Shrooms", Illegal = true, Location = 2},
    {Label = "Pipe Bomb", Illegal = true, Location = 2},
    {Label = "Molotov", Illegal = true, Location = 2},
}

---------------------------------------------------------------------------------
-------------------------------Ped Bio Configs-----------------------------------
---------------------------------------------------------------------------------
SDC.AgeRange = {Min = 18, Max = 70} --Random Age Range For Locals

SDC.Names = { --All Name Settings For locals
    Firstname = { --All Firstnames for Locals
        Male = { --All Male Names For Locals
            --EX: "FIRSTNAME",

            "Tyrone",
            "Josh",
            "Connor",
            "Jake",
            "John",
            "Lane",
            "Gunner",
            "Gannon",
            "Tyler",
            "Preston",
            "Tynan",
            "Mason",
            "Manny",
            "Will",
            "William",
            "Brandon",
            "Aiden",
            "Andy",
            "Anderson",
            "Ron",
            "Freddy",
            "Kaden",
            "Liam",
            "James",
            "Noah",
            "Oliver",
            "Theodore",
            "Lucas",
            "Levi",
            "Ezra",
            "Michael",
            "Sam",
            "Samuel",
            "Leo",
            "Henry",
            "Jack",
            "Daniel",
            "Ben",
            "Robert",
            "Jesus",
            "Richard",
            "Chris",
            "Charles",
            "Mathew",
            "Matt",
            "Anthony",
            "Thomas",
            "Donald",
            "Steven",
            "Kevin",
            "Mark"
        },
        Female = { --All Female Names For Locals
            --EX: "FIRSTNAME",

            "Lexi",
            "Mary",
            "Patricia",
            "Linda",
            "Jennifer",
            "Elizabeth",
            "Barbara",
            "Susan",
            "Jessica",
            "Karen",
            "Sarah",
            "Lisa",
            "Nancy",
            "Sandra",
            "Betty",
            "Ashley",
            "Emily",
            "Kimberly",
            "Donna",
            "Margaret",
            "Michelle",
            "Carol",
            "Amanda",
            "Melissa",
            "Deborah",
            "Stephanie",
            "Rebecca",
            "Sharon",
            "Laura",
            "Cynthia",
            "Dorothy",
            "Amy",
            "Kathleen",
            "Angela",
            "Nicole",
            "Anna",
            "Pamela",
            "Debra",
            "Janet",
            "Maria"
        }
    },
    Lastname = {  --All Lastnames for Locals
        --EX: "LASTNAME",

        "Walters",
        "Smith",
        "Brown",
        "Tremblay",
        "Martin",
        "Roy",
        "Gagnon",
        "Lee",
        "Wilson",
        "Johnson",
        "MacDonald",
        "Morin",
        "Butch",
        "Woods",
        "Winter",
        "Jones",
        "Miller",
        "Davis",
        "Garcia",
        "Wilson",
        "Martinez",
        "Anderson",
        "Taylor",
        "Jackson",
        "Harris",
        "White",
        "Hall",
        "Sanchez",
        "Adams",
        "Baker",
        "Flores",
        "Morris",
        "Collins",
        "Edwards",
        "Murphy",
        "Rogers",
        "Reed",
        "Howard"
    }
}

SDC.ModelToGender = { --All models to gender matching (DO NOT TOUCH)
    Male = {
        "a_m_m_acult_01",
        "a_m_m_afriamer_01",
        "a_m_m_beach_01",
        "a_m_m_beach_02",
        "a_m_m_bevhills_01",
        "a_m_m_bevhills_02",
        "a_m_m_business_01",
        "a_m_m_eastsa_01",
        "a_m_m_eastsa_02",
        "a_m_m_farmer_01",
        "a_m_m_fatlatin_01",
        "a_m_m_genfat_01",
        "a_m_m_genfat_02",
        "a_m_m_golfer_01",
        "a_m_m_hasjew_01",
        "a_m_m_hillbilly_01",
        "a_m_m_hillbilly_02",
        "a_m_m_indian_01",
        "a_m_m_ktown_01",
        "a_m_m_malibu_01",
        "a_m_m_mexcntry_01",
        "a_m_m_mexlabor_01",
        "a_m_m_og_boss_01",
        "a_m_m_paparazzi_01",
        "a_m_m_polynesian_01",
        "a_m_m_prolhost_01",
        "a_m_m_rurmeth_01",
        "a_m_m_salton_01",
        "a_m_m_salton_02",
        "a_m_m_salton_03",
        "a_m_m_salton_04",
        "a_m_m_skater_01",
        "a_m_m_skidrow_01",
        "a_m_m_socenlat_01",
        "a_m_m_soucent_01",
        "a_m_m_soucent_02",
        "a_m_m_soucent_03",
        "a_m_m_soucent_04",
        "a_m_m_stlat_02",
        "a_m_m_tennis_01",
        "a_m_m_tourist_01",
        "a_m_m_tramp_01",
        "a_m_m_trampbeac_01",
        "a_m_m_tranvest_01",
        "a_m_m_tranvest_02",
        "a_m_o_acult_01",
        "a_m_o_acult_02",
        "a_m_o_beach_01",
        "a_m_o_genstreet_01",
        "a_m_o_ktown_01",
        "a_m_o_salton_01",
        "a_m_o_soucent_01",
        "a_m_o_soucent_02",
        "a_m_o_soucent_03",
        "a_m_o_tramp_01",
        "a_m_y_acult_01",
        "a_m_y_acult_02",
        "a_m_y_beach_01",
        "a_m_y_beach_02",
        "a_m_y_beach_03",
        "a_m_y_beachvesp_01",
        "a_m_y_beachvesp_02",
        "a_m_y_bevhills_01",
        "a_m_y_bevhills_02",
        "a_m_y_breakdance_01",
        "a_m_y_busicas_01",
        "a_m_y_business_01",
        "a_m_y_business_02",
        "a_m_y_business_03",
        "a_m_y_clubcust_01",
        "a_m_y_clubcust_02",
        "a_m_y_clubcust_03",
        "a_m_y_cyclist_01",
        "a_m_y_dhill_01",
        "a_m_y_downtown_01",
        "a_m_y_eastsa_01",
        "a_m_y_eastsa_02",
        "a_m_y_epsilon_01",
        "a_m_y_epsilon_02",
        "a_m_y_gay_01",
        "a_m_y_gay_02",
        "a_m_y_genstreet_01",
        "a_m_y_genstreet_02",
        "a_m_y_golfer_01",
        "a_m_y_hasjew_01",
        "a_m_y_hiker_01",
        "a_m_y_hippy_01",
        "a_m_y_hipster_01",
        "a_m_y_hipster_02",
        "a_m_y_hipster_03",
        "a_m_y_indian_01",
        "a_m_y_jetski_01",
        "a_m_y_juggalo_01",
        "a_m_y_ktown_01",
        "a_m_y_ktown_02",
        "a_m_y_latino_01",
        "a_m_y_methhead_01",
        "a_m_y_mexthug_01",
        "a_m_y_motox_01",
        "a_m_y_motox_02",
        "a_m_y_musclbeac_01",
        "a_m_y_musclbeac_02",
        "a_m_y_polynesian_01",
        "a_m_y_roadcyc_01",
        "a_m_y_runner_01",
        "a_m_y_runner_02",
        "a_m_y_salton_01",
        "a_m_y_skater_01",
        "a_m_y_skater_02",
        "a_m_y_soucent_01",
        "a_m_y_soucent_02",
        "a_m_y_soucent_03",
        "a_m_y_soucent_04",
        "a_m_y_stbla_01",
        "a_m_y_stbla_02",
        "a_m_y_stlat_01",
        "a_m_y_stwhi_01",
        "a_m_y_stwhi_02",
        "a_m_y_sunbathe_01",
        "a_m_y_surfer_01",
        "a_m_y_vindouche_01",
        "a_m_y_vinewood_01",
        "a_m_y_vinewood_02",
        "a_m_y_vinewood_03",
        "a_m_y_vinewood_04",
        "a_m_y_yoga_01",
        "a_m_m_mlcrisis_01",
        "a_m_y_gencaspat_01",
        "a_m_y_smartcaspat_01",
        "cs_andreas",
        "cs_bankman",
        "cs_barry",
        "cs_beverly",
        "cs_brad",
        "cs_bradcadaver",
        "cs_carbuyer",
        "cs_casey",
        "cs_chengsr",
        "cs_chrisformage",
        "cs_clay",
        "cs_dale",
        "cs_davenorton",
        "cs_devin",
        "cs_dom",
        "cs_dreyfuss",
        "cs_drfriedlander",
        "cs_fabien",
        "cs_fbisuit_01",
        "cs_floyd",
        "cs_hunter",
        "cs_jimmyboston",
        "cs_jimmydisanto",
        "cs_joeminuteman",
        "cs_johnnyklebitz",
        "cs_josef",
        "cs_josh",
        "cs_lamardavis",
        "cs_lazlow",
        "cs_lazlow_2",
        "cs_lifeinvad_01",
        "cs_manuel",
        "cs_martinmadrazo",
        "cs_milton",
        "cs_movpremmale",
        "cs_mrk",
        "cs_nervousron",
        "cs_nigel",
        "cs_old_man1a",
        "cs_old_man2",
        "cs_omega",
        "cs_orleans",
        "cs_paper",
        "cs_priest",
        "cs_prolsec_02",
        "cs_russiandrunk",
        "cs_siemonyetarian",
        "cs_solomon",
        "cs_stevehains",
        "cs_stretch",
        "cs_taocheng",
        "cs_taostranslator",
        "cs_tenniscoach",
        "cs_terry",
        "cs_tom",
        "cs_tomepsilon",
        "cs_wade",
        "cs_zimbor",
        "csb_agent",
        "csb_alan",
        "csb_anton",
        "csb_avon",
        "csb_ballasog",
        "csb_bogdan",
        "csb_burgerdrug",
        "csb_car3guy1",
        "csb_car3guy2",
        "csb_chef",
        "csb_chef2",
        "csb_chin_goon",
        "csb_cletus",
        "csb_cop",
        "csb_customer",
        "csb_dix",
        "csb_englishdave",
        "csb_fos_rep",
        "csb_g",
        "csb_groom",
        "csb_grove_str_dlr",
        "csb_hao",
        "csb_hugh",
        "csb_imran",
        "csb_jackhowitzer",
        "csb_janitor",
        "csb_money",
        "csb_mp_agent14",
        "csb_mweather",
        "csb_ortega",
        "csb_oscar",
        "csb_popov",
        "csb_porndudes",
        "csb_prologuedriver",
        "csb_prolsec",
        "csb_ramp_gang",
        "csb_ramp_hic",
        "csb_ramp_hipster",
        "csb_ramp_marine",
        "csb_ramp_mex",
        "csb_rashcosvki",
        "csb_reporter",
        "csb_roccopelosi",
        "csb_sol",
        "csb_talcc",
        "csb_talmm",
        "csb_tonyprince",
        "csb_trafficwarden",
        "csb_undercover",
        "csb_vagspeak",
        "csb_avery",
        "csb_brucie2",
        "csb_thornton",
        "csb_tomcasino",
        "csb_vincent",
        "g_m_importexport_01",
        "g_m_m_armboss_01",
        "g_m_m_armgoon_01",
        "g_m_m_armlieut_01",
        "g_m_m_chemwork_01",
        "g_m_m_chiboss_01",
        "g_m_m_chicold_01",
        "g_m_m_chigoon_01",
        "g_m_m_chigoon_02",
        "g_m_m_korboss_01",
        "g_m_m_mexboss_01",
        "g_m_m_mexboss_02",
        "g_m_y_armgoon_02",
        "g_m_y_azteca_01",
        "g_m_y_ballaeast_01",
        "g_m_y_ballaorig_01",
        "g_m_y_ballasout_01",
        "g_m_y_famca_01",
        "g_m_y_famdnf_01",
        "g_m_y_famfor_01",
        "g_m_y_korean_01",
        "g_m_y_korean_02",
        "g_m_y_korlieut_01",
        "g_m_y_lost_01",
        "g_m_y_lost_02",
        "g_m_y_lost_03",
        "g_m_y_mexgang_01",
        "g_m_y_mexgoon_01",
        "g_m_y_mexgoon_02",
        "g_m_y_mexgoon_03",
        "g_m_y_pologoon_01",
        "g_m_y_pologoon_02",
        "g_m_y_salvaboss_01",
        "g_m_y_salvagoon_01",
        "g_m_y_salvagoon_02",
        "g_m_y_salvagoon_03",
        "g_m_y_strpunk_01",
        "g_m_y_strpunk_02",
        "g_m_m_casrn_01",
        "mp_g_m_pros_01",
        "mp_m_avongoon",
        "mp_m_boatstaff_01",
        "mp_m_bogdangoon",
        "mp_m_claude_01",
        "mp_m_cocaine_01",
        "mp_m_counterfeit_01",
        "mp_m_exarmy_01",
        "mp_m_execpa_01",
        "mp_m_famdd_01",
        "mp_m_fibsec_01",
        "mp_m_forgery_01",
        "mp_m_freemode_01",
        "mp_m_g_vagfun_01",
        "mp_m_marston_01",
        "mp_m_meth_01",
        "mp_m_niko_01",
        "mp_m_securoguard_01",
        "mp_m_shopkeep_01",
        "mp_m_waremech_01",
        "mp_m_weapexp_01",
        "mp_m_weapwork_01",
        "mp_m_weed_01",
        "mp_s_m_armoured_01",
        "s_m_m_ammucountry",
        "s_m_m_armoured_01",
        "s_m_m_armoured_02",
        "s_m_m_autoshop_01",
        "s_m_m_autoshop_02",
        "s_m_m_bouncer_01",
        "s_m_m_ccrew_01",
        "s_m_m_chemsec_01",
        "s_m_m_ciasec_01",
        "s_m_m_cntrybar_01",
        "s_m_m_dockwork_01",
        "s_m_m_doctor_01",
        "s_m_m_fiboffice_01",
        "s_m_m_fiboffice_02",
        "s_m_m_fibsec_01",
        "s_m_m_gaffer_01",
        "s_m_m_gardener_01",
        "s_m_m_gentransport",
        "s_m_m_hairdress_01",
        "s_m_m_highsec_01",
        "s_m_m_highsec_02",
        "s_m_m_janitor",
        "s_m_m_lathandy_01",
        "s_m_m_lifeinvad_01",
        "s_m_m_linecook",
        "s_m_m_lsmetro_01",
        "s_m_m_mariachi_01",
        "s_m_m_marine_01",
        "s_m_m_marine_02",
        "s_m_m_migrant_01",
        "s_m_m_movalien_01",
        "s_m_m_movprem_01",
        "s_m_m_movspace_01",
        "s_m_m_paramedic_01",
        "s_m_m_pilot_01",
        "s_m_m_pilot_02",
        "s_m_m_postal_01",
        "s_m_m_postal_02",
        "s_m_m_prisguard_01",
        "s_m_m_scientist_01",
        "s_m_m_security_01",
        "s_m_m_snowcop_01",
        "s_m_m_strperf_01",
        "s_m_m_strpreach_01",
        "s_m_m_strvend_01",
        "s_m_m_trucker_01",
        "s_m_m_ups_01",
        "s_m_m_ups_02",
        "s_m_o_busker_01",
        "s_m_y_airworker",
        "s_m_y_ammucity_01",
        "s_m_y_armymech_01",
        "s_m_y_autopsy_01",
        "s_m_y_barman_01",
        "s_m_y_baywatch_01",
        "s_m_y_blackops_01",
        "s_m_y_blackops_02",
        "s_m_y_blackops_03",
        "s_m_y_busboy_01",
        "s_m_y_chef_01",
        "s_m_y_clown_01",
        "s_m_y_clubbar_01",
        "s_m_y_construct_01",
        "s_m_y_construct_02",
        "s_m_y_cop_01",
        "s_m_y_dealer_01",
        "s_m_y_devinsec_01",
        "s_m_y_dockwork_01",
        "s_m_y_doorman_01",
        "s_m_y_dwservice_01",
        "s_m_y_dwservice_02",
        "s_m_y_factory_01",
        "s_m_y_fireman_01",
        "s_m_y_garbage",
        "s_m_y_grip_01",
        "s_m_y_hwaycop_01",
        "s_m_y_marine_01",
        "s_m_y_marine_02",
        "s_m_y_marine_03",
        "s_m_y_mime",
        "s_m_y_pestcont_01",
        "s_m_y_pilot_01",
        "s_m_y_prismuscl_01",
        "s_m_y_prisoner_01",
        "s_m_y_ranger_01",
        "s_m_y_robber_01",
        "s_m_y_sheriff_01",
        "s_m_y_shop_mask",
        "s_m_y_strvend_01",
        "s_m_y_swat_01",
        "s_m_y_uscg_01",
        "s_m_y_valet_01",
        "s_m_y_waiter_01",
        "s_m_y_waretech_01",
        "s_m_y_winclean_01",
        "s_m_y_xmech_01",
        "s_m_y_xmech_02",
        "s_m_y_casino_01",
        "s_m_y_westsec_01",
        "hc_driver",
        "hc_gunman",
        "hc_hacker",
        "ig_agent",
        "ig_andreas",
        "ig_avon",
        "ig_ballasog",
        "ig_bankman",
        "ig_barry",
        "ig_benny",
        "ig_bestmen",
        "ig_beverly",
        "ig_brad",
        "ig_car3guy1",
        "ig_car3guy2",
        "ig_casey",
        "ig_chef",
        "ig_chef2",
        "ig_chengsr",
        "ig_chrisformage",
        "ig_clay",
        "ig_claypain",
        "ig_cletus",
        "ig_dale",
        "ig_davenorton",
        "ig_devin",
        "ig_dix",
        "ig_djblamrupert",
        "ig_djblamryans",
        "ig_djdixmanager",
        "ig_djgeneric_01",
        "ig_djsolfotios",
        "ig_djsoljakob",
        "ig_djsolmanager",
        "ig_djsolmike",
        "ig_djsolrobt",
        "ig_djtalignazio",
        "ig_dom",
        "ig_dreyfuss",
        "ig_drfriedlander",
        "ig_englishdave",
        "ig_fabien",
        "ig_fbisuit_01",
        "ig_floyd",
        "ig_g",
        "ig_groom",
        "ig_hao",
        "ig_hunter",
        "ig_jay_norris",
        "ig_jimmyboston",
        "ig_jimmyboston_02",
        "ig_jimmydisanto",
        "ig_joeminuteman",
        "ig_johnnyklebitz",
        "ig_josef",
        "ig_josh",
        "ig_lamardavis",
        "ig_lazlow",
        "ig_lazlow_2",
        "ig_lestercrest",
        "ig_lestercrest_2",
        "ig_lifeinvad_01",
        "ig_lifeinvad_02",
        "ig_malc",
        "ig_manuel",
        "ig_milton",
        "ig_money",
        "ig_mp_agent14",
        "ig_mrk",
        "ig_nervousron",
        "ig_nigel",
        "ig_old_man1a",
        "ig_old_man2",
        "ig_omega",
        "ig_oneil",
        "ig_orleans",
        "ig_ortega",
        "ig_paper",
        "ig_popov",
        "ig_priest",
        "ig_prolsec_02",
        "ig_ramp_gang",
        "ig_ramp_hic",
        "ig_ramp_hipster",
        "ig_ramp_mex",
        "ig_rashcosvki",
        "ig_roccopelosi",
        "ig_russiandrunk",
        "ig_sacha",
        "ig_siemonyetarian",
        "ig_sol",
        "ig_solomon",
        "ig_stevehains",
        "ig_stretch",
        "ig_talcc",
        "ig_talina",
        "ig_talmm",
        "ig_taocheng",
        "ig_taostranslator",
        "ig_tenniscoach",
        "ig_terry",
        "ig_tomepsilon",
        "ig_tonyprince",
        "ig_trafficwarden",
        "ig_tylerdix",
        "ig_tylerdix_02",
        "ig_vagspeak",
        "ig_wade",
        "ig_zimbor",
        "player_one",
        "player_two",
        "player_zero",
        "ig_avery",
        "ig_brucie2",
        "ig_thornton",
        "ig_tomcasino",
        "ig_vincent",
        "u_m_m_aldinapoli",
        "u_m_m_bankman",
        "u_m_m_bikehire_01",
        "u_m_m_doa_01",
        "u_m_m_edtoh",
        "u_m_m_fibarchitect",
        "u_m_m_filmdirector",
        "u_m_m_glenstank_01",
        "u_m_m_griff_01",
        "u_m_m_jesus_01",
        "u_m_m_jewelsec_01",
        "u_m_m_jewelthief",
        "u_m_m_markfost",
        "u_m_m_partytarget",
        "u_m_m_prolsec_01",
        "u_m_m_promourn_01",
        "u_m_m_rivalpap",
        "u_m_m_spyactor",
        "u_m_m_streetart_01",
        "u_m_m_willyfist",
        "u_m_o_filmnoir",
        "u_m_o_finguru_01",
        "u_m_o_taphillbilly",
        "u_m_o_tramp_01",
        "u_m_y_abner",
        "u_m_y_antonb",
        "u_m_y_babyd",
        "u_m_y_baygor",
        "u_m_y_burgerdrug_01",
        "u_m_y_chip",
        "u_m_y_corpse_01",
        "u_m_y_cyclist_01",
        "u_m_y_danceburl_01",
        "u_m_y_dancelthr_01",
        "u_m_y_dancerave_01",
        "u_m_y_fibmugger_01",
        "u_m_y_guido_01",
        "u_m_y_gunvend_01",
        "u_m_y_hippie_01",
        "u_m_y_imporage",
        "u_m_y_juggernaut_01",
        "u_m_y_justin",
        "u_m_y_mani",
        "u_m_y_militarybum",
        "u_m_y_paparazzi",
        "u_m_y_party_01",
        "u_m_y_pogo_01",
        "u_m_y_prisoner_01",
        "u_m_y_proldriver_01",
        "u_m_y_rsranger_01",
        "u_m_y_sbike",
        "u_m_y_smugmech_01",
        "u_m_y_staggrm_01",
        "u_m_y_tattoo_01",
        "u_m_y_zombie_01",
        "u_m_m_blane",
        "u_m_m_curtis",
        "u_m_m_vince",
        "u_m_o_dean",
        "u_m_y_caleb",
        "u_m_y_croupthief_01",
        "u_m_y_gabriel",
        "u_m_y_ushi"
    },
    Female = {
        "a_f_m_beach_01",
        "a_f_m_bevhills_01",
        "a_f_m_bevhills_02",
        "a_f_m_beach_01",
        "a_f_m_bevhills_01",
        "a_f_m_bevhills_02",
        "a_f_m_bodybuild_01",
        "a_f_m_business_02",
        "a_f_m_downtown_01",
        "a_f_m_eastsa_01",
        "a_f_m_eastsa_02",
        "a_f_m_fatbla_01",
        "a_f_m_fatcult_01",
        "a_f_m_fatwhite_01",
        "a_f_m_ktown_01",
        "a_f_m_ktown_02",
        "a_f_m_prolhost_01",
        "a_f_m_salton_01",
        "a_f_m_skidrow_01",
        "a_f_m_soucent_01",
        "a_f_m_soucent_02",
        "a_f_m_soucentmc_01",
        "a_f_m_tourist_01",
        "a_f_m_tramp_01",
        "a_f_m_trampbeac_01",
        "a_f_o_genstreet_01",
        "a_f_o_indian_01",
        "a_f_o_ktown_01",
        "a_f_o_salton_01",
        "a_f_o_soucent_01",
        "a_f_o_soucent_02",
        "a_f_y_beach_01",
        "a_f_y_bevhills_01",
        "a_f_y_bevhills_02",
        "a_f_y_bevhills_03",
        "a_f_y_bevhills_04",
        "a_f_y_business_01",
        "a_f_y_business_02",
        "a_f_y_business_03",
        "a_f_y_business_04",
        "a_f_y_clubcust_01",
        "a_f_y_clubcust_02",
        "a_f_y_clubcust_03",
        "a_f_y_eastsa_01",
        "a_f_y_eastsa_02",
        "a_f_y_eastsa_03",
        "a_f_y_epsilon_01",
        "a_f_y_femaleagent",
        "a_f_y_fitness_01",
        "a_f_y_fitness_02",
        "a_f_y_genhot_01",
        "a_f_y_golfer_01",
        "a_f_y_hiker_01",
        "a_f_y_hippie_01",
        "a_f_y_hipster_01",
        "a_f_y_hipster_02",
        "a_f_y_hipster_03",
        "a_f_y_hipster_04",
        "a_f_y_indian_01",
        "a_f_y_juggalo_01",
        "a_f_y_runner_01",
        "a_f_y_rurmeth_01",
        "a_f_y_scdressy_01",
        "a_f_y_skater_01",
        "a_f_y_soucent_01",
        "a_f_y_soucent_02",
        "a_f_y_soucent_03",
        "a_f_y_tennis_01",
        "a_f_y_topless_01",
        "a_f_y_tourist_01",
        "a_f_y_tourist_02",
        "a_f_y_vinewood_01",
        "a_f_y_vinewood_02",
        "a_f_y_vinewood_03",
        "a_f_y_vinewood_04",
        "a_f_y_yoga_01",
        "a_f_y_gencaspat_01",
        "a_f_y_smartcaspat_01",
        "cs_amandatownley",
        "cs_ashley",
        "cs_debra",
        "cs_denise",
        "cs_guadalope",
        "cs_gurk",
        "cs_janet",
        "cs_jewelass",
        "cs_karen_daniels",
        "cs_lestercrest",
        "cs_magenta",
        "cs_marnie",
        "cs_maryann",
        "cs_michelle",
        "cs_molly",
        "cs_movpremf_01",
        "cs_mrs_thornhill",
        "cs_mrsphillips",
        "cs_natalia",
        "cs_patricia",
        "cs_tanisha",
        "cs_tracydisanto",
        "csb_abigail",
        "csb_anita",
        "csb_bride",
        "csb_bryony",
        "csb_denise_friend",
        "csb_djblamadon",
        "csb_maude",
        "csb_mrs_r",
        "csb_paige",
        "csb_screen_writer",
        "csb_stripper_01",
        "csb_stripper_02",
        "csb_tonya",
        "csb_agatha",
        "g_f_importexport_01",
        "g_f_importexport_01",
        "g_f_y_ballas_01",
        "g_f_y_families_01",
        "g_f_y_lost_01",
        "g_f_y_vagos_01",
        "mp_f_bennymech_01",
        "mp_f_boatstaff_01",
        "mp_f_cardesign_01",
        "mp_f_chbar_01",
        "mp_f_cocaine_01",
        "mp_f_counterfeit_01",
        "mp_f_deadhooker",
        "mp_f_execpa_01",
        "mp_f_execpa_02",
        "mp_f_forgery_01",
        "mp_f_freemode_01",
        "mp_f_helistaff_01",
        "mp_f_meth_01",
        "mp_f_misty_01",
        "mp_f_stripperlite",
        "mp_f_weed_01",
        "s_f_m_fembarber",
        "s_f_m_maid_01",
        "s_f_m_shop_high",
        "s_f_m_sweatshop_01",
        "s_f_y_airhostess_01",
        "s_f_y_bartender_01",
        "s_f_y_baywatch_01",
        "s_f_y_clubbar_01",
        "s_f_y_cop_01",
        "s_f_y_factory_01",
        "s_f_y_hooker_01",
        "s_f_y_hooker_02",
        "s_f_y_hooker_03",
        "s_f_y_migrant_01",
        "s_f_y_movprem_01",
        "s_f_y_ranger_01",
        "s_f_y_scrubs_01",
        "s_f_y_sheriff_01",
        "s_f_y_shop_low",
        "s_f_y_shop_mid",
        "s_f_y_stripper_01",
        "s_f_y_stripper_02",
        "s_f_y_stripperlite",
        "s_f_y_sweatshop_01",
        "s_f_y_casino_01",
        "ig_abigail",
        "ig_amandatownley",
        "ig_ashley",
        "ig_bride",
        "ig_denise",
        "ig_djblamadon",
        "ig_djtalaurelia",
        "ig_janet",
        "ig_jewelass",
        "ig_karen_daniels",
        "ig_kerrymcintosh",
        "ig_kerrymcintosh_02",
        "ig_lacey_jones_02",
        "ig_magenta",
        "ig_marnie",
        "ig_maryann",
        "ig_maude",
        "ig_michelle",
        "ig_molly",
        "ig_mrs_thornhill",
        "ig_mrsphillips",
        "ig_natalia",
        "ig_paige",
        "ig_patricia",
        "ig_screen_writer",
        "ig_tanisha",
        "ig_tonya",
        "ig_tracydisanto",
        "ig_agatha",
        "u_f_m_corpse_01",
        "u_f_m_miranda",
        "u_f_m_miranda_02",
        "u_f_m_promourn_01",
        "u_f_o_moviestar",
        "u_f_o_prolhost_01",
        "u_f_y_bikerchic",
        "u_f_y_comjane",
        "u_f_y_corpse_01",
        "u_f_y_corpse_02",
        "u_f_y_danceburl_01",
        "u_f_y_dancelthr_01",
        "u_f_y_dancerave_01",
        "u_f_y_hotposh_01",
        "u_f_y_jewelass_01",
        "u_f_y_mistress",
        "u_f_y_poppymich",
        "u_f_y_poppymich_02",
        "u_f_y_princess",
        "u_f_y_spyactress",
        "u_f_m_casinocash_01",
        "u_f_m_casinoshop_01",
        "u_f_m_debbie_01",
        "u_f_o_carol",
        "u_f_o_eileen",
        "u_f_y_beth",
        "u_f_y_lauren",
        "u_f_y_taylor"
    }
}